In [83]:
import pandas as pd
import numpy as np

In [84]:
df_mchas = pd.read_csv(r'C:\projects\MashChas\mash_chas\mash_chas.csv', sep=';')

In [85]:
df_mchas['period'] = pd.to_datetime(df_mchas['period'], dayfirst=True)

In [86]:
df_mchas['mnth'] = df_mchas['period'].dt.month_name()
df_mchas.tail()

,period,name,doljnost,type_ts,priznak,auto,time_work_putevoy,probeg,gsm_fact,Norma_gsm,...,time_work_speed,gsm_money,rent,salary_time,salary_probeg,remont,cost_time_pl,cost_avgspeed,cost_fuel,mnth
2952,2024-08-01,Щербинин Сергей Александрович,Машинист электростанции передвижной 7 разряда,ДЭС,М/ч,125070 AJ Power AJ550,400.0,477.0,5481.0,31.1,...,477.000000,2.084011e+06,0.00,177028.7900,177028.79,0.000000,5652.599295,4740.125195,12829.471850,August
2953,2024-08-01,Якутка Владимир Петрович,Водитель автомобиля 5 разряда,Автофургоны,Расстояние,117195 КамАЗ-43118-23027-50 АФ-57435С-02 Р467У...,279.0,569.0,200.0,6.2,...,15.378378,1.543140e+04,0.00,72561.2965,11110.85,69824.130000,565.651717,6266.355287,4892.321704,August
2954,2024-08-01,Якутка Владимир Петрович,Водитель автомобиля 5 разряда,Автоцистерны,Расстояние,118607 УРАЛ 5493Т Р466КС198,210.0,406.0,173.0,6.1,...,10.972973,1.334816e+04,0.00,53902.6774,7927.96,0.000000,320.242098,1938.957049,2371.272417,August
2955,2024-08-01,Якутка Владимир Петрович,Водитель автомобиля 5 разряда,Легковой а/м,Расстояние,"87027 MITSUBISHI L200 2,5 С563РС198",60.0,1006.0,82.0,2.4,...,27.189189,6.326875e+03,0.00,14512.2593,19644.15,4230.443333,417.826295,1110.789594,733.743738,August
2956,2024-08-01,Якутка Владимир Петрович,Водитель автомобиля 5 разряда,Легковой а/м,Расстояние,"87028 MITSUBISHI L200 2,5 С792РС198",259.0,8636.0,886.0,2.4,...,233.405405,6.836111e+04,18759.62,66341.7568,168635.03,148087.360000,1164.285137,1730.221813,816.839324,August

In [87]:
df_remont = pd.read_csv(r'C:\projects\MashChas\mash_chas\remont_mnth.csv', sep=';')
df_remont.head()

,period,auto,sum_remont,Cnt_at_mnth
0,01.01.2024,117022 УРАЛ 47441С М264ХЕ199,30391.40,2
1,01.01.2024,117023 УРАЛ 47441С М364ХЕ199,97935.69,0
2,01.01.2024,117031 УРАЛ 47441С О036ВВ198,30358.00,2
3,01.01.2024,117188 ГАЗ-320273 278819 М718ХЕ198,49315.90,1
4,01.01.2024,117191 КамАЗ-43118-23027-50 АФ-57435С-02 Р276С...,12436.05,2

In [88]:
df_remont['period'] = pd.to_datetime(df_remont['period'], dayfirst=True)

In [89]:
df_remont_0 = df_remont[df_remont['Cnt_at_mnth'] == 0]

In [90]:
df_remont_0['mnth'] = df_remont_0['period'].dt.month_name()

C:\Users\Михаил\AppData\Local\Temp\ipykernel_13396\2745857599.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_remont_0['mnth'] = df_remont_0['period'].dt.month_name()

In [91]:
df_remont_0

,period,auto,sum_remont,Cnt_at_mnth,mnth
1,2024-01-01,117023 УРАЛ 47441С М364ХЕ199,97935.69,0,January
20,2024-01-01,"86995 MITSUBISHI L200 2,5 Р509РК198",499129.18,0,January
27,2024-01-01,87011 Toyota Hiace Р946УР198,36666.67,0,January
35,2024-01-01,АО,97951.10,0,January
54,2024-02-01,123244 ЭД100-Т400-50-1РН-G1,302666.67,0,February
...,...,...,...,...,...
663,2024-08-01,160096 МДН 86.26-010,16000.00,0,August
664,2024-08-01,АО,5444.76,0,August
665,2024-08-01,АО,15000.00,0,August
666,2024-08-01,84354 УАЗ-390945 (Фермер) г/н А990ТХ89,1118.00,0,August
667,2024-08-01,117040 УРАЛ 47441С г/н К539НР197,2200.00,0,August

In [92]:
df_remont_0.groupby(['auto']).agg({'sum_remont': sum})

C:\Users\Михаил\AppData\Local\Temp\ipykernel_13396\3889102074.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df_remont_0.groupby(['auto']).agg({'sum_remont': sum})

                                                    sum_remont
auto
106018 УРАЛ 5942 FE ППУА 1600/100 О352ВТ198           93794.20
106041 УРАЛ 5942 FE ППУА 1600/100 О909ВС198           87662.56
107080 КамАЗ-65115 МКЗ-4804-02 (мусоровоз) М072СК7    53735.84
107160 КамАЗ МК-4546-08 Р906УО198 ТДУ                167127.59
107163 КамАЗ КО-449 Р931ТР198                        351600.16
...                                                        ...
Автомомобиль Toyota Camry VIN:XW7BF4FK50S044192...     6300.00
КАМАЗ 65117-N3  X1F651173D0000343 Р923ТС98             3190.00
УРАЛ 4320 Фургон грузовой изотермический 47441С...    33984.33
Штабелер самоходный LEMA SRL-1225 VIN:XEA212801...     4583.33
Электропогрузчик Ричтрак LEMA FRB-20105  VIN:от...     9550.00

[98 rows x 1 columns]

*Машчас покрутить*

In [93]:
our_cols = ['period', 'auto', 'type_ts', 'time_work_putevoy', 'probeg', 'gsm_fact', 'time_work_fuel', 'time_work_speed', 'rent', 'salary_time', 'salary_probeg', 'remont', 'cost_time_pl', 'cost_avgspeed', 'cost_fuel']

In [94]:
df = df_mchas[our_cols]
df.head()

,period,auto,type_ts,time_work_putevoy,probeg,gsm_fact,time_work_fuel,time_work_speed,rent,salary_time,salary_probeg,remont,cost_time_pl,cost_avgspeed,cost_fuel
0,2024-01-01,84674 УАЗ-220695-04 О057ВУ198,Легковой а/м,290.0,5597.0,863.0,287.666667,151.270270,0.000000,205518.540,205518.54,117462.5,1343.336353,2575.308035,1354.232477
1,2024-01-01,90721 SHACMAN SX32586V385 SX32 Р648УС198,Самосвалы,70.0,4.0,22.0,2.972973,1.000000,160850.533300,0.000,0.00,0.0,2322.114109,162547.987600,54675.232200
2,2024-01-01,117114 УРАЛ 47441В О022ЕА198,Автофургоны,50.0,109.0,70.0,11.290323,2.945946,456.323077,41182.660,41182.66,0.0,940.799480,15967.697600,4166.397698
3,2024-01-01,117189 ГАЗ-320273 278819 М740ХЕ198,Автофургоны,80.0,1428.0,217.0,35.000000,38.594595,44098.360000,216598.232,212427.05,0.0,3467.995798,7080.485875,7926.847539
4,2024-01-01,"87028 MITSUBISHI L200 2,5 С792РС198",Легковой а/м,10.0,208.0,25.0,10.416667,5.621622,18759.620000,26770.568,30941.75,8382.5,5584.161333,10675.353020,5360.794880

In [95]:
df_agg = df.groupby(['period', 'auto']).agg({
        'time_work_putevoy': sum,
        'probeg': sum,
        'gsm_fact': sum,
        'time_work_fuel': sum,
        'time_work_speed': sum,
        'rent': sum,
        'salary_time': sum,
        'salary_probeg': sum,
        'remont': sum,
        'cost_time_pl': sum,
        'cost_fuel': sum,
        'cost_avgspeed': sum
        }
        ).reset_index()

C:\Users\Михаил\AppData\Local\Temp\ipykernel_13396\1692610950.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df_agg = df.groupby(['period', 'auto']).agg({
C:\Users\Михаил\AppData\Local\Temp\ipykernel_13396\1692610950.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df_agg = df.groupby(['period', 'auto']).agg({

In [96]:
df_agg.head()

,period,auto,time_work_putevoy,probeg,gsm_fact,time_work_fuel,time_work_speed,rent,salary_time,salary_probeg,remont,cost_time_pl,cost_fuel,cost_avgspeed
0,2024-01-01,106018 УРАЛ 5942 FE ППУА 1600/100 О352ВТ198,80.0,0.0,48.0,4.705882,0.000000,48672.00000,13821.4167,0.00,0.0,827.461917,14066.852580,0.000000
1,2024-01-01,106247 УРАЛ 7098Т2 ППУ 1600/100 Р227РТ198,190.0,0.0,419.0,41.078431,0.000000,96291.74167,128296.1991,0.00,0.0,2797.004931,17700.494796,0.000000
2,2024-01-01,107159 КамАЗ МК-4546-08 Р641УУ198,300.0,943.0,672.0,120.000000,25.486486,116520.10000,219380.9740,206844.34,0.0,3039.439571,8419.029684,32152.114330
3,2024-01-01,107160 КамАЗ МК-4546-08 Р906УО198,310.0,1381.0,1030.0,183.928571,37.324324,116520.10000,259147.3800,259147.38,0.0,3955.190604,7694.503477,30028.230452
4,2024-01-01,107163 КамАЗ КО-449 Р931ТР198,310.0,837.0,384.0,68.571429,22.621622,96106.70833,205519.2000,205519.20,0.0,1068.561940,4830.790437,14643.256220

In [97]:
df_pivot = pd.pivot_table(
    df,
    index=['period','auto', 'type_ts']
).reset_index()

In [98]:
df_pivot

,period,auto,type_ts,cost_avgspeed,cost_fuel,cost_time_pl,gsm_fact,probeg,remont,rent,salary_probeg,salary_time,time_work_fuel,time_work_putevoy,time_work_speed
0,2024-01-01,106018 УРАЛ 5942 FE ППУА 1600/100 О352ВТ198,Парогенераторы,0.000000,14066.852580,827.461917,48.0,0.00,0.00,48672.000000,0.00,13821.41670,4.705882,80.0,0.000000
1,2024-01-01,106247 УРАЛ 7098Т2 ППУ 1600/100 Р227РТ198,Парогенераторы,0.000000,8850.247398,1398.502466,209.5,0.00,0.00,48145.870835,0.00,64148.09955,20.539216,95.0,0.000000
2,2024-01-01,107159 КамАЗ МК-4546-08 Р641УУ198,Коммунальная техника,16076.057165,4209.514842,1519.719785,336.0,471.50,0.00,58260.050000,103422.17,109690.48700,60.000000,150.0,12.743243
3,2024-01-01,107160 КамАЗ МК-4546-08 Р906УО198,Коммунальная техника,15014.115226,3847.251739,1977.595302,515.0,690.50,0.00,58260.050000,129573.69,129573.69000,91.964286,155.0,18.662162
4,2024-01-01,107163 КамАЗ КО-449 Р931ТР198,Коммунальная техника,14643.256220,4830.790437,1068.561940,384.0,837.00,0.00,96106.708330,205519.20,205519.20000,68.571429,310.0,22.621622
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1600,2024-08-01,90721 SHACMAN SX32586V385 SX32 Р648УС198,Самосвалы,5270.869550,3182.955829,3528.480501,251.0,672.75,0.00,40212.633325,24916.25,28608.15440,33.918919,32.5,18.182432
1601,2024-08-01,90841 КамАЗ 4590Е7 Р626УУ198,Самосвалы,12088.618490,1864.416136,1553.680114,834.0,1322.00,21441.70,115928.633300,240774.30,240774.30000,231.666667,278.0,35.729730
1602,2024-08-01,90842 КамАЗ 4590Е7 Р625УУ198,Самосвалы,23478.265780,2677.915666,2408.707213,340.0,400.50,17153.36,115928.633300,80238.31,79016.20400,94.444444,105.0,10.824324
1603,2024-08-01,93515 Mercedes-Benz-3341 Aсtros Р100ЕА89,Самосвалы,53574.651130,13765.428616,3701.339208,225.0,228.30,102703.68,67058.500000,68745.85,83084.89390,20.833333,75.0,6.170270
1604,2024-08-01,94053 Mercedes-Benz-3341 Aсtros О370ВА198,Самосвалы,28444.866820,8072.737315,2613.354812,465.0,494.50,29107.15,134117.000000,181059.64,148474.02880,43.055556,133.0,13.364865

In [99]:
unique_type_ts = list(df['type_ts'].unique())

In [100]:
unique_type_ts

['Легковой а/м',
 'Самосвалы',
 'Автофургоны',
 'Автоцистерны',
 'ДЭС',
 'Коммунальная техника',
 'Автобусы',
 'Погрузчики',
 'Мотопомпа',
 'Парогенераторы',
 'Строительная техника',
 'Болотоход',
 'Тягачи',
 'Бортовой автомобиль']

In [101]:
for i in unique_type_ts:
    print(i)

Легковой а/м
Самосвалы
Автофургоны
Автоцистерны
ДЭС
Коммунальная техника
Автобусы
Погрузчики
Мотопомпа
Парогенераторы
Строительная техника
Болотоход
Тягачи
Бортовой автомобиль

In [102]:
df['type_ts'].value_counts()

type_ts
Автоцистерны            904
Автофургоны             578
Легковой а/м            445
ДЭС                     324
Автобусы                196
Погрузчики              145
Самосвалы               143
Коммунальная техника    105
Мотопомпа                43
Парогенераторы           21
Строительная техника     21
Тягачи                   21
Болотоход                 7
Бортовой автомобиль       4
Name: count, dtype: int64

~Цистерны~

In [103]:
df_bochka = df[df['type_ts'] == 'Автоцистерны']

In [104]:
df_bochka

,period,auto,type_ts,time_work_putevoy,probeg,gsm_fact,time_work_fuel,time_work_speed,rent,salary_time,salary_probeg,remont,cost_time_pl,cost_avgspeed,cost_fuel
5,2024-01-01,118113 КамАЗ-56774-22 О038АА198,Автоцистерны,120.0,1575.0,997.00,163.442623,42.567568,3244.50000,112430.0400,112430.04,0.000000,1605.000685,4524.573360,1178.395689
9,2024-01-01,118067 УРАЛ 66173-0000013 О041ЕН198,Автоцистерны,125.0,597.0,501.00,82.131148,16.135135,0.00000,76641.6392,123050.39,18591.923330,1071.113809,11174.246480,1630.188183
10,2024-01-01,118005 УРАЛ 5675-G0 Т608ВН89,Автоцистерны,100.0,312.0,219.00,35.901639,8.432432,0.00000,107884.3300,107884.33,714.723333,1254.964392,14882.590550,3495.562919
15,2024-01-01,118051 УРАЛ 66173-0000013 О881СХ11,Автоцистерны,30.0,855.0,292.00,47.868852,23.108108,0.00000,26380.1370,32047.48,0.000000,1630.332829,2361.825884,1021.749684
16,2024-01-01,118492 УРАЛ 4320-1951-40 4672К7-10 Р714СЕ198,Автоцистерны,270.0,6183.0,2684.00,440.000000,167.108108,77924.78333,237421.2330,231753.89,0.000000,1934.946074,3092.417853,1187.353272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2941,2024-08-01,118594 УРАЛ 5493Т Р290РМ198,Автоцистерны,206.3,1888.0,612.00,100.327869,51.027027,0.00000,105960.2472,97006.66,425.000000,744.572658,2834.806583,1531.033611
2942,2024-08-01,118592 УРАЛ 5493Т Р850РО198,Автоцистерны,310.0,7339.0,2232.00,365.901639,198.351351,0.00000,246634.6400,246634.64,1250.000000,1355.158366,2117.954280,1148.120283
2945,2024-08-01,118271 УРАЛ 46151-01 Р539СА71,Автоцистерны,80.0,831.0,312.75,51.270492,22.459459,0.00000,16815.4288,11179.61,0.000000,511.828559,1572.186809,798.632571
2946,2024-08-01,118598 УРАЛ 5493Т Р609КН198,Автоцистерны,80.0,216.0,78.00,12.786885,5.837838,0.00000,16815.4288,2905.89,7942.160000,384.697948,2889.134214,2406.828187
2954,2024-08-01,118607 УРАЛ 5493Т Р466КС198,Автоцистерны,210.0,406.0,173.00,28.360656,10.972973,0.00000,53902.6774,7927.96,0.000000,320.242098,1938.957049,2371.272417

In [130]:
df_bochka_pivot = pd.pivot_table(
    df_bochka,
    index=['auto'],
    columns='period',
    values=['cost_fuel']
)

In [131]:
df_bochka_pivot

                                       cost_fuel                             \
period                                2024-01-01   2024-02-01    2024-03-01
auto
118005 УРАЛ 5675-G0 Т608ВН89         2646.948466  1658.119285   1988.383472
118011 УРАЛ 5675-G0 О039АЕ198                NaN          NaN  12572.696660
118024 УРАЛ 5666 О027ВТ198                   NaN   674.401087  17978.755780
118047 УРАЛ 66173-0000013 В306ХТ199   946.876318  1621.032457   2918.006226
118051 УРАЛ 66173-0000013 О881СХ11   1082.918202  1101.728083   1034.419644
...                                          ...          ...           ...
118608 УРАЛ 5493Т Р438КН198                  NaN          NaN           NaN
118609 УРАЛ 5493Т Р978МО198                  NaN          NaN           NaN
118610 УРАЛ 5493Т Р488КТ198                  NaN          NaN           NaN
118611 УРАЛ 5493Т Р463КС198                  NaN          NaN           NaN
118612 УРАЛ 5493Т Р473КН198                  NaN          NaN           NaN

                                                                             \
period                                 2024-04-01   2024-05-01   2024-06-01
auto
118005 УРАЛ 5675-G0 Т608ВН89          4551.003408  3367.777888  2994.699129
118011 УРАЛ 5675-G0 О039АЕ198         1129.423717  1838.261764     0.000000
118024 УРАЛ 5666 О027ВТ198                    NaN          NaN          NaN
118047 УРАЛ 66173-0000013 В306ХТ199   2767.364630  2996.602329  3447.172624
118051 УРАЛ 66173-0000013 О881СХ11     931.378987  1470.226088  3018.646165
...                                           ...          ...          ...
118608 УРАЛ 5493Т Р438КН198                   NaN          NaN          NaN
118609 УРАЛ 5493Т Р978МО198          73380.765450   802.951653  4417.394155
118610 УРАЛ 5493Т Р488КТ198          73380.765450          NaN          NaN
118611 УРАЛ 5493Т Р463КС198          73380.765450          NaN          NaN
118612 УРАЛ 5493Т Р473КН198          73380.765450          NaN          NaN


period                                2024-07-01   2024-08-01
auto
118005 УРАЛ 5675-G0 Т608ВН89         5819.902722  3994.382339
118011 УРАЛ 5675-G0 О039АЕ198                NaN          NaN
118024 УРАЛ 5666 О027ВТ198                   NaN          NaN
118047 УРАЛ 66173-0000013 В306ХТ199          NaN          NaN
118051 УРАЛ 66173-0000013 О881СХ11   2305.168297  1751.033382
...                                          ...          ...
118608 УРАЛ 5493Т Р438КН198                  NaN  4275.267325
118609 УРАЛ 5493Т Р978МО198          1653.993539  1411.497014
118610 УРАЛ 5493Т Р488КТ198                  NaN          NaN
118611 УРАЛ 5493Т Р463КС198          1128.666702  4847.419499
118612 УРАЛ 5493Т Р473КН198                  NaN  3435.635285

[70 rows x 8 columns]

In [143]:
df_null_gsm = df_bochka[df_bochka['cost_fuel'] == 0]
df_null_gsm

,period,auto,type_ts,time_work_putevoy,probeg,gsm_fact,time_work_fuel,time_work_speed,rent,salary_time,salary_probeg,remont,cost_time_pl,cost_avgspeed,cost_fuel
357,2024-02-01,118047 УРАЛ 66173-0000013 В306ХТ199,Автоцистерны,NaN,0.0,0.0,0.0,0.0,0.00000,0.0000,0.00,0.000,0.000000,0.0000,0.0
392,2024-02-01,118245 УРАЛ 66173-0000012 В970РА197,Автоцистерны,10.0,0.0,0.0,0.0,0.0,0.00000,50316.7100,0.00,0.000,5031.671000,0.0000,0.0
649,2024-02-01,118112 КамАЗ-56774-22 О038ЕК198,Автоцистерны,30.0,0.0,0.0,0.0,0.0,3244.50000,16341.3909,0.00,0.000,652.863030,0.0000,0.0
752,2024-03-01,118211 УРАЛ 66173-0000012 А400УК89,Автоцистерны,1.0,0.0,0.0,0.0,0.0,0.00000,0.0000,0.00,0.000,0.000000,0.0000,0.0
827,2024-03-01,118224 УРАЛ 66173-0000012 О040АМ198,Автоцистерны,10.0,0.0,0.0,0.0,0.0,0.00000,11014.3080,0.00,0.000,1101.430800,0.0000,0.0
848,2024-03-01,118224 УРАЛ 66173-0000012 О040АМ198,Автоцистерны,NaN,0.0,0.0,0.0,0.0,0.00000,0.0000,0.00,0.000,0.000000,0.0000,0.0
996,2024-03-01,118601 УРАЛ 5493Т Р741РУ198,Автоцистерны,20.0,0.0,0.0,0.0,0.0,184318.18330,15082.8502,0.00,0.000,9970.051677,0.0000,0.0
1470,2024-05-01,118191 УРАЛ 66173-0000012 О663ЕР89,Автоцистерны,10.0,0.0,0.0,0.0,0.0,0.00000,9819.8452,0.00,79738.190,8955.803520,0.0000,0.0
1713,2024-05-01,118594 УРАЛ 5493Т Р290РМ198,Автоцистерны,10.0,3.0,0.0,0.0,1.0,164918.69170,4115.4924,105.72,0.000,16903.418410,165024.4117,0.0
1778,2024-06-01,118011 УРАЛ 5675-G0 О039АЕ198,Автоцистерны,110.0,0.0,0.0,0.0,0.0,0.00000,27698.1486,0.00,0.000,251.801351,0.0000,0.0
1840,2024-06-01,118298 УРАЛ 567521 Р785ОК198,Автоцистерны,70.0,0.0,0.0,0.0,0.0,0.00000,31484.7195,0.00,0.000,449.781707,0.0000,0.0
2610,2024-08-01,118492 УРАЛ 4320-1951-40 4672К7-10 Р714СЕ198,Автоцистерны,10.0,0.0,0.0,0.0,0.0,77924.78333,105786.4005,0.00,130555.000,31426.618380,0.0000,0.0
2629,2024-08-01,118162 УРАЛ 46151-01 Р271УО198,Автоцистерны,1.0,0.0,0.0,0.0,0.0,0.00000,0.0000,0.00,0.000,0.000000,0.0000,0.0
2649,2024-08-01,118211 УРАЛ 66173-0000012 А400УК89,Автоцистерны,1.0,0.0,0.0,0.0,0.0,0.00000,3417.1200,0.00,0.000,3417.120000,0.0000,0.0
2762,2024-08-01,118492 УРАЛ 4320-1951-40 4672К7-10 Р714СЕ198,Автоцистерны,1.0,0.0,0.0,0.0,0.0,0.00000,1331.4303,0.00,130555.000,131886.430300,0.0000,0.0
2777,2024-08-01,118172 УРАЛ 46151-01 Р280УО198,Автоцистерны,1.0,0.0,0.0,0.0,0.0,0.00000,14793.6800,0.00,17500.000,32293.680000,0.0000,0.0
2924,2024-08-01,118433 УРАЛ 5493Т Р566НУ198,Автоцистерны,30.0,0.0,0.0,0.0,0.0,0.00000,0.0000,0.00,3098.685,103.289500,0.0000,0.0

In [141]:
df_uniq_auto = list(df_null_gsm['auto'].unique())
df_uniq_auto

['118047 УРАЛ 66173-0000013 В306ХТ199',
 '118245 УРАЛ 66173-0000012 В970РА197',
 '118112 КамАЗ-56774-22 О038ЕК198',
 '118211 УРАЛ 66173-0000012 А400УК89',
 '118224 УРАЛ 66173-0000012 О040АМ198',
 '118601 УРАЛ 5493Т Р741РУ198',
 '118191 УРАЛ 66173-0000012 О663ЕР89',
 '118594 УРАЛ 5493Т Р290РМ198',
 '118011 УРАЛ 5675-G0 О039АЕ198',
 '118298 УРАЛ 567521 Р785ОК198',
 '118492 УРАЛ 4320-1951-40 4672К7-10 Р714СЕ198',
 '118162 УРАЛ 46151-01 Р271УО198',
 '118172 УРАЛ 46151-01 Р280УО198',
 '118433 УРАЛ 5493Т Р566НУ198']

In [142]:
len(df_uniq_auto)

14